management:
  endpoints:
    web:
      exposure:
        include: '*'
        
spring:
  datasource:
    url: jdbc:postgresql://john.db.elephantsql.com:5432/miismcbf?createDatabaseIfNotExist=true
    username: miismcbf
    password: ZUEZ_eZe-dTqWgestZyYchEZwcj0vWG0
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        